
version: 2

models:
  - name: seg_user_order
    description: "products dbt model"
    columns:
      - name: user_id
        description: "The primary key for this table"
        tests:
          - not_null
      - name: order_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null